// JsFromRoutes CacheKey 3a06b0915918ed7d8ba7bc5b2bf48223
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/posts'),
  create: /* #__PURE__ */ definePathHelper('post', '/posts'),
  show: /* #__PURE__ */ definePathHelper('get', '/posts/:id'),
}
