// JsFromRoutes CacheKey 8ec77376c8b2e24b6e951251de881358
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/posts'),
  show: /* #__PURE__ */ definePathHelper('get', '/posts/:id'),
}
